### ISSUE TITLE
Remove hardcoding of image OS's

### ISSUE THREAD

**Issue by gabipetrovay** [stephenplusplus/gce-images#3]
The image OS URLs are hardcoded [here](https://github.com/stephenplusplus/gce-images/blob/master/index.js#L20-L29).

Why don't you pick them up using:

``` sh
gcloud compute images list --uri
```

or the REST API:

```
GET https://www.googleapis.com/compute/v1/projects/project/global/images
```

Of course this means you have to give `gce-images` a scope (the project). Can't gre-images instead get an `gcloud` instance (that contains all this info: auth, project, etc.)

**Comment by stephenplusplus** [comment]
Well, the idea was to let a user use this lib without having any system dependencies (gcloud sdk) or auth credentials.

What does the global/images response look like?

**Comment by gabipetrovay** [comment]
```
https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-6-v20151104
https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20151104
https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-alpha-845-0-0-v20151025
https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-beta-835-4-0-v20151110
https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-stable-766-5-0-v20151105
https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/backports-debian-7-wheezy-v20151104
https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-7-wheezy-v20151104
https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-8-jessie-v20151104
https://www.googleapis.com/compute/v1/projects/google-containers/global/images/container-vm-v20151103
https://www.googleapis.com/compute/v1/projects/opensuse-cloud/global/images/opensuse-13-1-v20150822
https://www.googleapis.com/compute/v1/projects/opensuse-cloud/global/images/opensuse-13-2-v20150511
https://www.googleapis.com/compute/v1/projects/rhel-cloud/global/images/rhel-6-v20151104
https://www.googleapis.com/compute/v1/projects/rhel-cloud/global/images/rhel-7-v20151104
https://www.googleapis.com/compute/v1/projects/suse-cloud/global/images/sles-11-sp4-v20150714
https://www.googleapis.com/compute/v1/projects/suse-cloud/global/images/sles-12-v20150511
https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1204-precise-v20150910
https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1404-trusty-v20150909a
https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1504-vivid-v20150911
https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1510-wily-v20151026
https://www.googleapis.com/compute/v1/projects/windows-cloud/global/images/windows-server-2008-r2-dc-v20151006
https://www.googleapis.com/compute/v1/projects/windows-cloud/global/images/windows-server-2012-r2-dc-v20151006
```

**Comment by stephenplusplus** [comment]
Alrighty, let's ditch the static OS_URLS and pull from there. Would you mind throwing a PR together?

**Comment by gabipetrovay** [comment]
In this case, wouldn't it be better to implement it in [gcloud compute API](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.24.1/compute) and leave it here static like this?

**Comment by stephenplusplus** [comment]
That's actually why I created this library; instead of growing gcloud-node's responsibilities, I wanted to start plucking them out when it might apply for other use cases that don't require gcloud-node.

I don't think this list will update too frequently, so I can go either way...

  1. keep the statics and try to stay up to date. When a new one comes up, if I don't catch it, the community might (like you did), or...
  1. require a project ID and always have the latest, but force users to provide auth as well

I'm kind of right on the fence... you make the call! :P

**Comment by gabipetrovay** [comment]
1

**Comment by stephenplusplus** [comment]
Awesome. Added you to the repo & npm perms, hope you continue to help out!

**Comment by gabipetrovay** [comment]
Sure! Thanks!
